steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "staging-qual-us-docker.pkg.dev/sdlc-og-test/og-test/nginx:latest", "."]
images: ["staging-qual-us-docker.pkg.dev/sdlc-og-test/og-test/nginx:latest"]
options:
  requestedVerifyOption: VERIFIED
  logging: CLOUD_LOGGING_ONLY
